### ISSUE TITLE
fix the facebook login

### ISSUE THREAD

**Issue by robeleq** [Meteor-Addis/community-home#8]
i don't know why its not working for me.

**Comment by ghost** [comment]
accidentally replaced the fb secret & appId when merging, can you try now

**Comment by hilawi** [comment]
@robikieq did that fix the problem or are you experiencing some other issue? Could you post more details?

**Comment by robeleq** [comment]
hi Hilawi ,  now it is working and i can login locally, so 10x for the fix.

**Comment by hilawi** [comment]
Great! Closing this.
